Z = [10 40 ; 0.5 -1] ;
B = [1 ; 0] ;
I = inv(Z) * B ; 
Rth = 1/I(1) ;
L = 6;
Ii = 6 ;
tc = L/Rth ;
t_final = 5*tc ;
t = 0:1e-2 :2  ;
I_t = Ii *exp(-t/tc) ;
figure ;
plot(t, I_t , 'r' ) ;
grid ;
xlabel('Time(in sec)') ;
ylabel('I(t) ') ;
title('Transient Response');
set( gca , 'Fontsize' ,19) ;
h_xlabel = get(gca , 'xlabel') ;
set(h_xlabel , 'Fontsize' , 19) ;
legend('Inductor Current ') ;
